# Default values for k8ssandra-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  type: "cassandra"
  version: "4.0.6"

topology:
  datacenters:
    - name: "dc1"
      size: 1
      racks:
        - name: "rack1"
          # nodeAffinityLabels:
          #   kubernetes.io/topology-zone: "us-east1-a"

resources:
  requests:
    cpu: "1000m"
    memory: "1Gi"
    storage:
      class: "standard"
      size: "1Gi"

config:
  jvmOptions:
    heapSize: 512M

reaper:
  ui:
    username: "reaper"
    password: "reaper"
  cql:
    username: "reaper"
    password: "reaper"

medusa:
  provider: "s3_compatible"
  s3_compatible:
    bucketName: "k8ssandra-medusa"
    prefix: "test"
    host: "minio.minio.svc.cluster.local"
    port: 9000
    secure: false
    access_key: "FOOBARBAZ"
    secret_key: "FOOBARBAZ"
