apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | trunc 53 }}-reaper-ui
data:
  username: {{ .Values.reaper.ui.username | b64enc }}
  password: {{ .Values.reaper.ui.password | b64enc }}
